import { Captaincy, Positions } from './enum';
import { PlayerDisplay } from './model';

export const defaultPlayer = {
  id: 0,
  name: '',
  captaincy: null,
  team: {
    id: 0,
    name: '',
    code: 0,
    draw: 0,
    form: null,
    loss: 0,
    played: 0,
    points: 0,
    position: 0,
    short_name: '',
    strength: 0,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 0,
    strength_overall_away: 0,
    strength_attack_home: 0,
    strength_attack_away: 0,
    strength_defence_home: 0,
    strength_defence_away: 0,
    pulse_id: 0,
  },
  sub: null,
  price: 0,
  totalPoints: 0,
  roundPoints: 0,
  next_fixture: -1,
  toSwap: false,
  toTransfer: false,
  position: Positions.GKP,
};

export const defaultEleven: PlayerDisplay[] = [
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.GKP,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: { subPriority: 0 },
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.GKP,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.DEF,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.DEF,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.DEF,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.DEF,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: { subPriority: 1 },
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.DEF,
  },

  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.MID,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.MID,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.MID,
  },
  {
    id: -1,
    name: '',
    captaincy: Captaincy.C,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.MID,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: { subPriority: 2 },
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.MID,
  },

  {
    id: -1,
    name: '',
    captaincy: Captaincy.VC,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.FWD,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: null,
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.FWD,
  },
  {
    id: -1,
    name: '',
    captaincy: null,
    team: { id: 0, name: '', short_code: '' },
    sub: { subPriority: 3 },
    price: 0,
    totalPoints: 0,
    roundPoints: 0,
    toSwap: false,
    toTransfer: false,
    position: Positions.FWD,
  },
];
